#!/usr/bin/env bash
# selftest.sh — calibrate precommit-scan.sh against known-bad fixtures.
#
# House rule: an instrument that cannot reproduce the defect cannot certify its absence.
# Every check must fire on a planted defect here before a CLEAN reading from the scanner
# is worth anything. Invoked as `precommit-scan.sh --selftest`.

set -uo pipefail
SCAN="${1:-${BASH_SOURCE[0]%/*}/precommit-scan.sh}"
FIX="$(mktemp -d)"; REPO="$(mktemp -d)"
trap 'rm -rf "$FIX" "$REPO"' EXIT

# ---------------------------------------------------------------------------
# fixture A — plain tree, exercises the grep + filesystem checks
# ---------------------------------------------------------------------------
mkdir -p "$FIX/scenes" "$FIX/docs" "$FIX/tools"
cat > "$FIX/bad.gd" <<'GD'
extends Node
var x := clamp(a, 0.0, 1.0)
var y = expf(2.0)
var f = TEXTURE_FILTER_INHERIT
var z := ["a","b"][i]
var s = "%g" % v
func _boot(): DisplayServer.window_set_mode(0)
var fwd = transform.basis.z
var arr.edges = [1,2]
func t1(): assert_true(script.can_instantiate())
func t2(): assert_eq(d, Vector2i(3,4))
func t3(): var p = get_global_mouse_position()
func _initialize(): add_child(n)
var cb = func(v): total = total + v
GD
cat > "$FIX/scenes/bad.tscn" <<'TS'
[gd_scene load_steps=2 format=3]
[sub_resource type="AnimationNodeStateMachineTransition" id="1"]
advance_condition = &"go"
[node name="S" type="Sprite2D"]
region_rect = Rect2(0, 0, 0, 0)
speed = null
TS
printf '# GENERATED by tool\n[gd_resource type="Resource" format=3]\n' > "$FIX/bad.tres"
printf 'x' > "$FIX/docs/diagram.svg"
printf '#!/bin/sh\ngodot --headless --path . scene.tscn --my-flag=1\n' > "$FIX/tools/run.sh"

OUT_A="$(bash "$SCAN" --all --project "$FIX" 2>&1)"

# ---------------------------------------------------------------------------
# fixture B — real git repo, exercises #69 (uid orphan) and #76 (plugin strip)
# ---------------------------------------------------------------------------
(
  cd "$REPO" || exit 1
  git init -q . 2>/dev/null
  git config user.email t@t; git config user.name t
  printf 'config_version=5\n[editor_plugins]\nenabled=PackedStringArray("res://addons/godot-ai/plugin.cfg", "res://addons/gut/plugin.cfg")\n' > project.godot
  printf 'extends Node\n' > existing.gd
  git add -A >/dev/null 2>&1; git commit -qm base >/dev/null 2>&1
  # #69: new script committed WITHOUT its .uid twin
  printf 'extends Node\n' > new_script.gd
  printf 'uid://bxyz789\n' > new_script.gd.uid
  git add new_script.gd >/dev/null 2>&1          # deliberately NOT the .uid
  # #76: headless --import stripped a plugin out of the enabled list
  printf 'config_version=5\n[editor_plugins]\nenabled=PackedStringArray("res://addons/gut/plugin.cfg")\n' > project.godot
  git add project.godot >/dev/null 2>&1
) || { echo "SELFTEST: FAIL — could not build git fixture"; exit 2; }

OUT_B="$(bash "$SCAN" --staged --project "$REPO" 2>&1)"

# ---------------------------------------------------------------------------
# verdict
# ---------------------------------------------------------------------------
echo "=== fixture A (grep + filesystem checks) ==="
echo "$OUT_A" | sed 's/^/  /'
echo
echo "=== fixture B (git-backed checks: #69, #76) ==="
echo "$OUT_B" | sed 's/^/  /'
echo

EXPECT_A="2 12 20 44 60 1 17 18 28 39 32 26 9 3 8 15 58 7 72"
EXPECT_B="69 76"
MISSING=""; N_EXPECT=0

for id in $EXPECT_A; do
  N_EXPECT=$((N_EXPECT+1))
  echo "$OUT_A" | grep -qE "> #$id " || MISSING="$MISSING A/#$id"
done
for id in $EXPECT_B; do
  N_EXPECT=$((N_EXPECT+1))
  echo "$OUT_B" | grep -qE "> #$id " || MISSING="$MISSING B/#$id"
done

# negative control: a clean tree must NOT produce findings
CLEAN="$(mktemp -d)"; printf 'extends Node\nvar x: float = clampf(a, 0.0, 1.0)\n' > "$CLEAN/ok.gd"
OUT_C="$(bash "$SCAN" --all --project "$CLEAN" 2>&1)"
rm -rf "$CLEAN"
FALSE_POS=""
echo "$OUT_C" | grep -q '^VERDICT: CLEAN' || FALSE_POS="clean-tree produced findings"

echo "=== SELFTEST RESULT ==="
if [ -n "$MISSING" ]; then
  echo "SELFTEST: FAIL — checks did not fire on known-bad fixture:$MISSING"
  exit 2
fi
if [ -n "$FALSE_POS" ]; then
  echo "SELFTEST: FAIL — $FALSE_POS"
  echo "$OUT_C" | sed 's/^/    /'
  exit 2
fi
echo "SELFTEST: PASS — all $N_EXPECT checks fired on known-bad input, and a clean tree read CLEAN"
exit 0
